### ISSUE TITLE
fix: TUI shows developer name as author of `agama-pw` project 

### ISSUE THREAD

**Issue by ossdhaval** [GluuFederation/agama-pw#23]
Author should be `Gluufederation` as shown on the Agama Lab, explore section listing.

![image](https://github.com/user-attachments/assets/4e9384b5-5a1d-44c7-8bc2-94020463ab54)

**Comment by mmrraju** [comment]
Please check with latest release [v1.0.2](https://github.com/GluuFederation/agama-pw/releases) .

**Comment by ossdhaval** [comment]
Yes, this is fixed. Can you please link the relevant PR and close this issue?

**Comment by mmrraju** [comment]
@ossdhaval, no PR, Just login to [GluuFederation/agama-pw](https://github.com/GluuFederation/agama-pw) and make a new release from agama lab. I'm closing this issue.
